# Basic
title: 上善若水，人淡如菊 | 任玉飞
subtitle: 上善若水，人淡如菊
description: 嗨，我是任玉飞 (@Raphcel)，一名走在iOS开发路上的从业者，努力成为一个全栈工程师，爱好唱歌，以及所有与音乐有关的事情。目前在北京工作。吾笃信：认真你就赢了。
creator: <a href="http://yufei.ren">@halfrost</a>

url: "http://vno.onevcat.com"

permalink: /:year/:month/:title/

# Format
highlighter: rouge
markdown: kramdown
#redcarpet:
#  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript", tables]

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: black

# The blog button should not be removed.
blog_button:
    title: 博客
    description: Visit blog

# Navigation buttons in the front page.
nav:
    - {title: 关于, description: 关于, url: 'http://about.yufei.ren'}
    # - {title: Another Button, description: A button, url: 'http://example.com'}

# Pagination
gems: [jekyll-paginate]
paginate: 10
paginate_path: "blog/page/:num/"

# Comment
comment:
    disqus: halfrostsfield
    # duoshuo:vno-jekyll

# Social
social:
    weibo: halfrost
    github: halfrost
    jianshu: halfrost
    #gplus: 113872186786618065577
    mail: renyufei8023@gamil.com


# Google Analytics
ga:
    # id: your_ga_id
    # host: your_host
